### ISSUE TITLE
Queue problem caused by plugin?

### ISSUE THREAD

**Issue by sunscreem** [mister-bk/craft-mix#2]
Hey,

Love this plug in, have it on all my client sites.

I've got this problem on just one (commerce) site.

The queue manager is reporting failed with the following error:

```
The command "'/usr/bin/php7.3' '/home/forge/[redacted].com/craft' 'queue/exec' '55267' '300' '1' '0' '--verbose=1' '--color='" failed. Exit Code: 1(General error) Working directory: / Output: ================ Error Output: ================ Exception 'LogicException' with message 'Unable to register extension "misterbk\mix\twigextensions\MixTwigExtension" as extensions have already been initialized.' in /home/forge/[redacted].com/vendor/twig/twig/src/ExtensionSet.php:145 Stack trace: #0 /home/forge/[redacted].com/vendor/twig/twig/src/Environment.php(702): Twig\ExtensionSet->addExtension(Object(misterbk\mix\twigextensions\MixTwigExtension)) #1 /home/forge/[redacted].com/vendor/craftcms/cms/src/web/View.php(345): Twig\Environment->addExtension(Object(misterbk\mix\twigextensions\MixTwigExtension)) #2 /home/forge/[redacted].com/vendor/misterbk/mix/src/Mix.php(48): craft\web\View->registerTwigExtension(Object(misterbk\mix\twigextensions\MixTwigExtension)) #3 /home/forge/[redacted].com/vendor/yiisoft/yii2/base/BaseObject.php(109): misterbk\mix\Mix->init() #4 /home/forge/[redacted].com/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array) #5 /home/forge/[redacted].com/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('mix', Object(craft\console\Application), Array) #6 [internal function]: craft\base\Plugin->__construct('mix', Object(craft\console\Application), Array) #7 /home/forge/[redacted].com/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array) #8 /home/forge/[redacted].com/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('misterbk\\mix\\Mi...', Array, Array) #9 /home/forge/[redacted].com/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('misterbk\\mix\\Mi...', Array, Array) #10 /home/forge/[redacted].com/vendor/craftcms/cms/src/services/Plugins.php(908): yii\BaseYii::createObject(Array, Array) #11 /home/forge/[redacted].com/vendor/craftcms/cms/src/services/Plugins.php(227): craft\services\Plugins->createPlugin('mix', Array) #12 /home/forge/[redacted].com/vendor/craftcms/cms/src/base/ApplicationTrait.php(1416): craft\services\Plugins->loadPlugins() #13 /home/forge/[redacted].com/vendor/craftcms/cms/src/console/Application.php(61): craft\console\Application->_postInit() #14 /home/forge/[redacted].com/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init() #15 /home/forge/[redacted].com/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array) #16 /home/forge/[redacted].com/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array) #17 /home/forge/[redacted].com/vendor/craftcms/cms/src/console/Application.php(50): yii\console\Application->__construct(Array) #18 [internal function]: craft\console\Application->__construct(Array) #19 /home/forge/[redacted].com/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array) #20 /home/forge/[redacted].com/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array) #21 /home/forge/[redacted].com/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array) #22 /home/forge/[redacted].com/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array) #23 /home/forge/[redacted].com/vendor/craftcms/cms/bootstrap/console.php(51): require('/home/forge/jam...') #24 /home/forge/[redacted].com/craft(21): require('/home/forge/jam...') #25 {main}
```

**Comment by sunscreem** [comment]
Sorry - that formatted horribly.
